### ISSUE TITLE
There's no up-to-date tracking of the version releases with tags and/or release

### ISSUE THREAD

**Issue by heynan0** [webdiscus/webpack-remove-empty-scripts#12]
One of the projects I work on upgraded this package to a higher major version. Usually I have to verify the CHANGELOG to make sure the changes will not break the project. 

I found a file in https://github.com/webdiscus/webpack-remove-empty-scripts/blob/master/CHANGELOG.md

But I also think it would be nice if you could track the changes using any the following:

* branch for specific version
* tag for the specific version
  * Seems like there were some tags, but they are out of date and the newer releases haven't been tagged. Last one was `0.8.0`. Latest version on npmjs is `1.0.1`
* release entry (https://github.com/webdiscus/webpack-remove-empty-scripts/releases)
  * I saw the releases page is out of sync with the actual versions that have been released. Last one was for `0.8.0`.

**Comment by webdiscus** [comment]
Hi @heynan0,

You're right. Release information must be kept in sync with the NPM version.
But the latest version of NPM may not be stable. I usually wait 1 month after the NPM release and when all the bugs are fixed, no more critical issues are found, I make a stable release on GitHub.

If you see the latest v0.8.0 release on GitHub, then this is the latest stable proofed release.

Now, the lastest stable release is `v1.0.1`.

**Comment by heynan0** [comment]
@webdiscus I appreciate your response. Assuming `1.0.0` wouldn't be stable, have you thought about holding off on publishing to npmjs if you think it's not stable enough? I say this because Dependabot update pull requests are made based on that, so some projects might get automated upgrades like mine did. Example: https://github.com/usertest-swimm/demo-sentry/pull/22

From what I read you make a stable release on GitHub. What if you did the opposite? You can release on GitHub "beta" (or whatever you want to call it) versions (through branch workflow or "beta" tag + releases page). That is in addition to usual versions. Then, the stable ones get published to npmjs. That way, assuming `1.0.0` is unstable, I think Dependabot updates, for example, won't take the unstable versions into consideration in automated pull requests.

(I apologize if I got something wrong about the flow. I assumed from what I read that the version `1.0.0` published to npmjs was not stable)

**Comment by webdiscus** [comment]
@heynan0 

Each published NPM version is covered with tests for all features. From my side this version is already stable. But sometime somebody developer has special use case that to predict is impossible. I fix the issue, cover this rare use case with tests. When in 1 month nobody has an issue I create on GitHub stable release.

Beta version on NPM has no sense. I haved over one year a betta 1.0.0 version in NPM. During 1 year was only 2 downloads. Nobody will download beta version and as a consequence never will be found issues/(special use cases).

In this package is implemented all what needs for now. I support it for some rare use cases and update some dependencies.

If you see the changelog, in v1.0.1 was updated readme only.

I recommend to use exact version in packages.json:
```js
"webpack-remove-empty-scripts": "1.0.1"
```
Also, w/o prefixes such as `^` `~`.
If all you projects works, don't update this package, because this package is already mature and perfect, there is no room for improvement. Configure your Dependabot to ignore this package.
